from datetime import datetime
from typing import Optional

from pydantic import BaseModel

from .models import MessageSource, RiskLevel


class IncomingMessage(BaseModel):
    """What the Android app sends for every SMS/email it wants checked."""

    user_id: int
    source: MessageSource
    sender: str
    body_text: str
    subject: Optional[str] = None
    # Optional RFC 5322 Reply-To value extracted by the trusted email intake.
    # A domain mismatch is a weak signal only because legitimate services can differ.
    reply_to: Optional[str] = None
    # Optional for email only. This must be the Authentication-Results value
    # generated by the receiving provider (for example Gmail), not an arbitrary
    # same-named header trusted from inside the incoming message.
    authentication_results: Optional[str] = None
    # Computed on-device (Contacts lookup for SMS, Gmail history/People API for email) --
    # the backend has no access to either, so this arrives as a plain fact, not a tool call.
    is_known_sender: bool = False
    received_at: datetime


class CheckResponse(BaseModel):
    message_id: int
    risk_level: RiskLevel
    reason: str


class UserCreate(BaseModel):
    username: str
    phone_number: str
    gmail: str


class FamilyMemberCreate(BaseModel):
    user_id: int
    username: str
    phone_number: str
    telegram_chat_id: Optional[str] = None
